config/routes.rb
Rails.application.routes.draw do
  get 'tasks/new', to: 'task#new'
  post 'tasks', to: 'task#create', as: :create_task

  get 'tasks/:id/edit', to: 'task#edit', as: :edit
  patch 'tasks/:id', to: 'task#update', as: :update
  delete 'tasks/:id', to: 'task#destroy', as: :delete
  get 'tasks/:id', to: 'task#show', as: :task
  get 'tasks', to: 'task#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @tasks = Task.find(params[:id])
  end

  def edit
    @tasks = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params_task)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def update
    @tasks = Task.find(params[:id])
    @tasks.update(params_task)
    redirect_to tasks_path
    # if @task.save
    #   redirect_to tasks_path
    # else
    #   render :new
    # end
  end

  def destroy
    @tasks = Task.find(params[:id])
    @tasks.delete
    redirect_to tasks_path
  end

  private

  def params_task
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task/edit.html.erb
<%= form_for @tasks do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/task/index.html.erb
<h1>My Tasks#show</h1>
<p>
<% @tasks.each do |tsk| %>
<%= check_box tsk.completed, "disabled", {}, "false", "true" %>
<%= check_box "tsk", "completed", {:checked => tsk.completed, :disabled => true}%>

<%= link_to tsk.title, task_path(tsk) %>

<%= link_to 'Delete', delete_path(tsk), method: :delete, data:{ confirm: "Are you sure?"} %>

</p>
<% end %>

<%= link_to "add new task", tasks_new_path %>

app/views/task/new.html.erb
<%= form_for @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

<%= link_to "go back", tasks_path %>

app/views/task/show.html.erb
<h1>Task#edit</h1>

<p>
<%= link_to "Edit this task", edit_path(@tasks) %>
</p>

<p><%= @tasks.details %></p>
<p>

<%= check_box "@tasks", "completed", {:checked => @tasks.completed, :disabled => true}%> This task is
<br>

<%= link_to "go back", tasks_path %>
</p>